screen -X -S gazebo kill
screen -X -S remote kill
screen -X -S amcl kill
screen -X -S gmapping kill
screen -X -S movebase kill
screen -X -S rviz kill
screen -X -S nav kill
screen -X -S rosbridge kill
screen -X -S frontier kill
